name: apptime
description: App Android para consciência e redução do uso compulsivo do celular.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  fl_chart: ^0.70.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1A1D2E"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
